service: threemay
useDotenv: true

plugins:
  - serverless-esbuild

resources: ${file(./resources.yaml)}

functions:
  AddComment:
    handler: handlers/api/comments/add-comment/index.handler
    name: ${self:custom.servicePrefix}-add-comment
    events:
      - httpApi:
          path: /items/{itemId}/comment
          method: POST
          authorizer:
            name: ApiGatewayAuthorizer

  DeleteComment:
    handler: handlers/api/comments/delete-comment/index.handler
    name: ${self:custom.servicePrefix}-delete-comment
    events:
      - httpApi:
          path: /items/{itemId}/comment/{commentId}
          method: DELETE
          authorizer:
            name: ApiGatewayAuthorizer

  EditComment:
    handler: handlers/api/comments/edit-comment/index.handler
    name: ${self:custom.servicePrefix}-edit-comment
    events:
      - httpApi:
          path: /items/{itemId}/comment/{commentId}
          method: PUT
          authorizer:
            name: ApiGatewayAuthorizer

  PostItem:
    handler: handlers/api/items/post-item/index.handler
    name: ${self:custom.servicePrefix}-post-item
    events:
      - httpApi:
          path: /items/{status}
          method: POST
          authorizer:
            name: ApiGatewayAuthorizer

  GetItems:
    handler: handlers/api/items/get-items/index.handler
    name: ${self:custom.servicePrefix}-get-items
    events:
      - httpApi:
          path: /items
          method: GET
          authorizer:
            name: ApiGatewayAuthorizer

  DeleteItem:
    handler: handlers/api/items/delete-item/index.handler
    name: ${self:custom.servicePrefix}-delete-item
    events:
      - httpApi:
          path: /items/{itemId}
          method: DELETE
          authorizer:
            name: ApiGatewayAuthorizer

  GetSingleItem:
    handler: handlers/api/items/get-item/index.handler
    name: ${self:custom.servicePrefix}-get-item
    events:
      - httpApi:
          path: /items/{itemId}
          method: GET
          authorizer:
            name: ApiGatewayAuthorizer

  UpdateItem:
    handler: handlers/api/items/update-item/index.handler
    name: ${self:custom.servicePrefix}-update-item
    events:
      - httpApi:
          path: /items/{itemId}
          method: PUT
          authorizer:
            name: ApiGatewayAuthorizer

  SearchItems:
    handler: handlers/api/items/search-items/index.handler
    name: ${self:custom.servicePrefix}-search-items
    events:
      - httpApi:
          path: /items/search
          method: GET
          authorizer:
            name: ApiGatewayAuthorizer

  GetUser:
    handler: handlers/api/users/get-user/index.handler
    name: ${self:custom.servicePrefix}-get-user
    events:
      - httpApi:
          path: /users
          method: GET
          authorizer:
            name: ApiGatewayAuthorizer

  DeleteUser:
    handler: handlers/api/users/delete-user/index.handler
    name: ${self:custom.servicePrefix}-delete-user
    events:
      - httpApi:
          path: /users
          method: DELETE
          authorizer:
            name: ApiGatewayAuthorizer

  UpdateUser:
    handler: handlers/api/users/update-user/index.handler
    name: ${self:custom.servicePrefix}-update-user
    events:
      - httpApi:
          path: /user
          method: PUT
          authorizer:
            name: ApiGatewayAuthorizer

  SignUp:
    handler: handlers/api/auth/sign-up/index.handler
    name: ${self:custom.servicePrefix}-sign-up
    events:
      - httpApi:
          path: /signup
          method: POST

  SignIn:
    handler: handlers/api/auth/sign-in/index.handler
    name: ${self:custom.servicePrefix}-sign-in
    events:
      - httpApi:
          path: /signin
          method: POST

  ConfirmSignUp:
    handler: handlers/api/auth/confirm/index.handler
    name: ${self:custom.servicePrefix}-confirm-sign-up
    events:
      - httpApi:
          path: /confirm
          method: POST

  ValidateToken:
    handler: handlers/api/auth/validate-token/index.handler
    name: ${self:custom.servicePrefix}-validate-token
    events:
      - httpApi:
          path: /token
          method: GET
          authorizer:
            name: ApiGatewayAuthorizer

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 30
  environment:
    USER_POOL_CLIENT_ID:
      Ref: UserPoolClient
    USER_POOL_ID:
      Ref: UserPool
    MONGO_URL: ${env:MONGO_URL}
    STAGE: ${self:provider.stage}
    IMAGES_BUCKET_NAME:
      Ref: ImagesBucket
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:*
            - s3:*
          Resource: '*'
  httpApi:
    cors: true
    authorizers:
      ApiGatewayAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Sub:
            - 'https://cognito-idp.${aws:region}.amazonaws.com/${UserPoolId}'
            - UserPoolId: !Ref UserPool
        audience:
          - Ref: UserPoolClient

custom:
  servicePrefix: ${self:service}-${self:provider.stage}
  esbuild:
    bundle: true
    minify: true
    packager: pnpm
