service: threemay

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  timeout: 30
  environment:
    MONGO_URL: ${env:MONGO_URL}
    STAGE: ${self:provider.stage}

custom:
  servicePrefix: ${self:service}-${self:provider.stage}
  customVariable1: Hello, World!
  esbuild:
    bundle: true
    minify: true
    packager: pnpm

functions:
  # Serverless Framework specific syntax
  Function1:
    handler: handlers/api/function1/index.handler
    name: ${self:custom.servicePrefix}-function1
    events:
      - httpApi:
          path: /api/Function1
          method: GET
    environment:
      CUSTOM_VAR: ${self:custom.customVariable1}

  # Function2:
  #   handler: handlers/api/function2/index.handler
  #   name: ${self:custom.servicePrefix}-function2
  #   timeout: 10 # override global setting
  #   memorySize: 2048 # override default 512 Mb
  #   events:
  #     - schedule:
  #         rate: cron(0 12 * * ? *) # triggers every 12 hours
  #         enabled: true
