service: threemay
useDotenv: true

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 30
  environment:
    MONGO_URL: ${env:MONGO_URL}
    STAGE: ${self:provider.stage}

custom:
  servicePrefix: ${self:service}-${self:provider.stage}
  customVariable1: Hello, World!
  esbuild:
    bundle: true
    minify: true
    packager: pnpm

functions:
  PostItem:
    handler: handlers/api/post-item/index.handler
    name: ${self:custom.servicePrefix}-post-item
    events:
      - httpApi:
          path: /items/{status}
          method: POST

  GetItems:
    handler: handlers/api/get-items/index.handler
    name: ${self:custom.servicePrefix}-get-items
    events:
      - httpApi:
          path: /items/{status}
          method: GET

  # Function2:
  #   handler: handlers/api/function2/index.handler
  #   name: ${self:custom.servicePrefix}-function2
  #   timeout: 10 # override global setting
  #   memorySize: 2048 # override default 512 Mb
  #   events:
  #     - schedule:
  #         rate: cron(0 12 * * ? *) # triggers every 12 hours
  #         enabled: true
