service: threemay
useDotenv: true

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 30
  environment:
    MONGO_URL: ${env:MONGO_URL}
    STAGE: ${self:provider.stage}

custom:
  servicePrefix: ${self:service}-${self:provider.stage}
  customVariable1: Hello, World!
  esbuild:
    bundle: true
    minify: true
    packager: pnpm

functions:
  PostItem:
    handler: handlers/api/items/post-item/index.handler
    name: ${self:custom.servicePrefix}-post-item
    events:
      - httpApi:
          path: /items/{status}
          method: POST

  GetItems:
    handler: handlers/api/items/get-items/index.handler
    name: ${self:custom.servicePrefix}-get-items
    events:
      - httpApi:
          path: /items/{status}
          method: GET

  DeleteItem:
    handler: handlers/api/items/delete-item/index.handler
    name: ${self:custom.servicePrefix}-delete-item
    events:
      - httpApi:
          path: /items/{itemId}
          method: DELETE

  GetSingleItem:
    handler: handlers/api/items/get-item/index.handler
    name: ${self:custom.servicePrefix}-get-item
    events:
      - httpApi:
          path: /items/{itemId}
          method: GET

  UpdateItem:
    handler: handlers/api/items/update-item/index.handler
    name: ${self:custom.servicePrefix}-update-item
    events:
      - httpApi:
          path: /items/{itemId}
          method: PUT

  SearchItems:
    handler: handlers/api/items/search-items/index.handler
    name: ${self:custom.servicePrefix}-search-items
    events:
      - httpApi:
          path: /items/search
          method: GET

  AddUser:
    handler: handlers/api/users/add-user/index.handler
    name: ${self:custom.servicePrefix}-add-user
    events:
      - httpApi:
          path: /users
          method: POST

  GetUser:
    handler: handlers/api/users/get-user/index.handler
    name: ${self:custom.servicePrefix}-get-user
    events:
      - httpApi:
          path: /users/{userId}
          method: GET

  DeleteUser:
    handler: handlers/api/users/delete-user/index.handler
    name: ${self:custom.servicePrefix}-delete-user
    events:
      - httpApi:
          path: /users/{userId}
          method: DELETE

  UpdateUser:
    handler: handlers/api/user/update-user/index.handler
    name: ${self:custom.servicePrefix}-update-user
    events:
      - httpApi:
          path: /user/{userId}
          method: PUT
